### ISSUE TITLE
provide a hex package

### ISSUE THREAD

**Issue by Licenser** [inaka/elvis_core#7]
This requires the dependencies to be availalbe via hex too
Regarding this I already opened:
- [ ] https://github.com/ErlyORM/aleppo/issues/16
- [x] https://github.com/inaka/zipper/issues/22
- [ ] https://github.com/unbalancedparentheses/erlang-katana/issues/29

Once they are closed we should be able to use them in deps and use rebar3 hex upload to generate a elvis_core hex package :D

**Comment by elbrujohalcon** [comment]
I would be much happier if we could add hex.pm integration to erlang.mk … but for know, we can do it _the rebar3 way_

**Comment by Licenser** [comment]
This is more a requirement of hex then of rebar3, hex packages can't specify dependencies that are not packages themselves. What tool uploads them, rebar, mix, erlang.mk or some curl doesn't matter.

**Comment by tsloughter** [comment]
Right, it doesn't matter what tool is used to publish to hex, all that matters is that all dependencies are in hex. Publishing with rebar3 or mix (or any other tool that gets support) is fine.

**Comment by jfacorro** [comment]
Is it really necessary to have all dependencies in hex? Doesn't it depend on what tool is used to build the project. For example, if I'm building my project with `make` (using `erlang.mk`) and `elvis_core` is a dep that we get from hex.pm, `erlang.mk` will download its package and try to build it, since it has a `Makefile` with its own deps everything should work. I imagine the same scenario is valid when using `rebar`, `rebar3` or `mix` as long as the package contains a `rebar.config` file. Am I wrong?

**Comment by tsloughter** [comment]
Rebar3 resolves all deps of a hex package based on the registry, it will not fetch additional deps that are defined in rebar.config.

**Comment by jfacorro** [comment]
@tsloughter Oh, I see. I didn't know that. Thanks!
